// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQW-54hoMQPxDHob0iilhwvY3siLANRtY',
    appId: '1:711252118138:web:9183915707991cb0ec09c3',
    messagingSenderId: '711252118138',
    projectId: 'play-smart-92ef4',
    authDomain: 'play-smart-92ef4.firebaseapp.com',
    storageBucket: 'play-smart-92ef4.firebasestorage.app',
    measurementId: 'G-F0M8YW63TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqZiyJmijr_XjGRrLN7Ah6GLqukjLxMrQ',
    appId: '1:711252118138:android:5404332deb3360e5ec09c3',
    messagingSenderId: '711252118138',
    projectId: 'play-smart-92ef4',
    storageBucket: 'play-smart-92ef4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdyvwK5xjoRQO18zDJmj_VhpAmM4yWjSo',
    appId: '1:711252118138:ios:da790de203f80a6aec09c3',
    messagingSenderId: '711252118138',
    projectId: 'play-smart-92ef4',
    storageBucket: 'play-smart-92ef4.firebasestorage.app',
    iosBundleId: 'com.elitescout.playSmart',
  );
}
